# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import qrcode
import scan
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(480, 688)
        MainWindow.setStyleSheet(u"QWidget#centralwidget{\n"
                                 "	\n"
                                 "	background-color: rgb(184, 215, 255);\n"
                                 "\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 20, 241, 51))
        self.label.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.select = QtWidgets.QComboBox(self.centralwidget)
        self.select.setGeometry(QtCore.QRect(160, 100, 161, 41))
        self.select.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.select.setObjectName("select")
        self.select.addItem("")
        self.select.addItem("")
        self.wrote = QtWidgets.QTextEdit(self.centralwidget)
        self.wrote.setGeometry(QtCore.QRect(70, 230, 371, 201))
        self.wrote.setStyleSheet("background-color: rgb(255, 243, 235);\n""font: 16pt \"MS Shell Dlg 2\";")
        self.wrote.setObjectName("wrote")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(180, 500, 141, 61))
        self.submit.setStyleSheet("background-color: rgb(255, 243, 235);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.submit.setObjectName("submit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.submit.clicked.connect(self.submitted)
        self.scan = QtWidgets.QPushButton(self.centralwidget)
        self.scan.setObjectName(u"scan")
        self.scan.setGeometry(QtCore.QRect(370, 650, 91, 31))
        self.scan.setStyleSheet(u"background-color: rgb(255, 243, 235);\n"
                                "font: 12pt \"MS Shell Dlg 2\";")
        self.scan.clicked.connect(self.scanned)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Make QRCode"))
        self.select.setItemText(0, _translate("MainWindow", "Text"))
        self.select.setItemText(1, _translate("MainWindow", "Links"))
        self.submit.setText(_translate("MainWindow", "Make"))
        self.scan.setText(_translate("MainWindow", u"Scan"))

    def submitted(self):
        if self.select.currentText() == "Text":
            qr_text = self.wrote.toPlainText()
            img = qrcode.make(self.wrote.toPlainText())
            qr_list = list(qr_text)
            if len(qr_text) > 3:
                till_five = qr_list[0:5]
                to_string = ""
                for x in till_five:
                    to_string += x
            else:
                to_string = ""
                till_four = qr_list[0:3]
                for x in till_four:
                    to_string += x
        else:
            qr_text = self.wrote.toPlainText()
            img = qrcode.make(f"https://{self.wrote.toPlainText()}")
            qr_list = list(qr_text)
            if len(qr_text) > 3:
                till_five = qr_list[0:5]
                to_string = ""
                for x in till_five:
                    to_string += x
            else:
                to_string = ""
                till_four = qr_list[0:3]
                for x in till_four:
                    to_string += x

        img.save(f"{to_string}.png")
    def scanned(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = scan.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
